version: '3.9'
services:
  cache:
    image: redis
    ports:
      - '6379:6379'
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: urs-test-1
    volumes:
      - ${DB_HOST_PATH}:${DB_CONTAINER_PATH}
    ports:
      - '5433:5432'
  engine:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      HOST_IP_ADDR: ${HOST_IP_ADDR}
    extra_hosts:
      - ${HOST_LABEL}:${HOST_IP_ADDR}
    depends_on:
      - db
      - cache
    ports:
      - '5000:8000'
      - '5001:8001'
volumes:
  db:
    external: true
