FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install pm2 -g
RUN pm2 install pm2-logrotate
RUN pm2 set pm2-logrotate:max_size 50M
RUN pm2 set pm2-logrotate:retain 10
RUN pm2 set pm2-logrotate:compress true

RUN npm install

# RUN apk --no-cache add curl
# RUN apk add busybox-extras

# Bundle app source
COPY . .

EXPOSE 6379 5432
CMD [ "pm2-runtime", "start", "dev.config.js"]

