FROM node:alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install pm2 -g
RUN npm install

# Bundle app source
COPY . .


EXPOSE 5000
CMD [ "pm2-runtime", "start", "dev.config.js", "--only", "scraper"]
